version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: ch_admin
      CLICKHOUSE_PASSWORD: ch_admin_password
      # отключите для продакшена автосоздание БД/пользователя, а пароль храните в секретах
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok'"]
      interval: 10s
      timeout: 3s
      retries: 10

  superset-db:
    image: postgres:16-alpine
    container_name: superset-db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - superset_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset -d superset"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: superset-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - superset_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    depends_on:
      clickhouse:
        condition: service_healthy
      superset-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "change-me-to-a-long-random-string"
      # Метаданные Superset
      DATABASE_URL: postgresql+psycopg2://superset:superset@superset-db:5432/superset
      # Кеш и очереди
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # (опционально) часовой пояс
      TZ: Europe/Berlin
    volumes:
      - superset_home:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8088/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20

  # Одноразовая инициализация Superset (создание админа, миграции, первичный init)
  superset-init:
    build:
      context: ./superset
      dockerfile: Dockerfile
    depends_on:
      superset-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: "change-me-to-a-long-random-string"
      DATABASE_URL: postgresql+psycopg2://superset:superset@superset-db:5432/superset
      REDIS_HOST: redis
      REDIS_PORT: 6379
    entrypoint: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin
        --username admin
        --firstname Admin
        --lastname User
        --email admin@example.com
        --password admin &&
      superset init
      "
    restart: "no"

volumes:
  ch_data:
  ch_logs:
  superset_db:
  superset_redis:
  superset_home:
